services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    container_name: "gitlab"
    hostname: "gitlab.anas.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.anas.com'
    ports:
      - "80:80"
      - "2222:2222"
    volumes:
      - "./config:/etc/gitlab"
      - "./logs:/var/log/gitlab"
      - "./data:/var/opt/gitlab"
    networks:
      - gitlab

  gitlab-runner:
    image: "gitlab/gitlab-runner:latest"
    depends_on:
      - gitlab
    environment:
      GIT_SSL_NO_VERIFY: "1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config-runner:/etc/gitlab-runner"
    ports:
      - "8093:8093"
    restart: unless-stopped
    networks:
      - gitlab
networks:
  gitlab:
    driver: bridge
